config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'

  get 'about'   => 'static#about'
  get 'signup' => 'assassins#new'

  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get  'players/:id/defeat', to: 'players#defeat', as: 'defeat_player'
  patch 'players/:id/vanquish', to: 'players#vanquish', as: 'vanquish_player'

  resources :assassins
  resources :games do
    member do
      put :join
      put :start
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
	require 'securerandom'

	has_one :admin, class_name: "Assassin", foreign_key: "admin_id"
	has_many :players

	validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
	validates :description, presence: true, length: { maximum: 150 }
	validates_presence_of :admin

	def admin
		Assassin.find_by_id(self.admin_id)
	end

	def players
		Player.where(game_id: self.id)
	end

	def enrolling
		!self.finished && !self.in_progress
	end

	def status
		if self.finished
			"Completed"
		elsif self.in_progress
			"In-Progress"
		else
			"Enrolling"
		end
	end		

	def start
		self.update_attributes(in_progress: true)
		contestants = players.clone.shuffle
		contestants.each_with_index do |contestant, index|
			if contestant == contestants.last
				contestant.update_attributes(target_id: contestants.first.id)
			else
				contestant.update_attributes(target_id: contestants[index + 1].id)
			end
			contestant.update_attributes(passcode: SecureRandom.hex(4))
		end
	end	

	def player_vanquished
		if self.players.where(alive: true).count < 2
			self.update_attributes(in_progress: false, finished: true)
		end
	end

	def winner
		if self.finished
			self.players.where(alive: true).first
		else
			nil
		end
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :game, only: [:show, :edit, :update, :destroy, :join, :start]
	before_action :admin_user, only: [:edit, :update]

	def show
		@game
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.create(game_params.merge(:admin_id => current_user.id))
		
		if @game.save
			flash[:success] = "Game created!"
			redirect_to @game
		else
			render 'new'
		end
	end

	def edit
		@game
	end

	def update
		if @game.update_attributes(game_params)
			flash[:success] = "Game Updated!"
			redirect_to @game
		else
			render 'edit'
		end
	end

	def index
		if params[:mode] == "assassin_only"
			@games = Game.all.select do |game|
				game.players.where(assassin_id: current_user.id).count > 0
			end
		else
			@games = Game.all
		end
	end

	def destroy
		@game.destroy
		flash[:success] = "Game deleted"
		redirect_to assassins_url
	end

	def join
		if @game.enrolling
			unless @game.players.find_by(assassin_id: current_user.id)
				Player.create(game: @game, :assassin => current_user)
			    flash[:success] = "Joined Game!"
			else
				flash[:danger] = "Already Joined Game!"
			end
		else
			flash[:danger] = "Game Closed to Enrollment"
		end
		redirect_to @game
	end

	def start
		if @game.enrolling
			if @game.players.count > 1
				@game.start
				flash[:success] = "Game Started!"
			else
				flash[:danger] = "Must Have Two or More Players to Start Game!"
			end
		else
			flash[:danger] = "Game Already Started!"
		end
		redirect_to @game
	end

	private
	def game_params
		params.require(:game).permit(:name, :description, :mode)
	end

	def game
		@game = Game.find(params[:id])
	end

	def admin_user
		redirect_to(root_url) unless current_user?(@game.admin)
	end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/_game.html.erb
<li>
	<%= link_to game.name, game %>
	<% if current_user.admin? || current_user.id == game.admin_id %>
    | <%= link_to "delete", game, method: :delete,
                                  data: { confirm: "You sure?" } %>
    |  <%= link_to "edit", edit_game_path(game) %>
    <% end %>
</li>

app/views/games/edit.html.erb
<% provide(:title, "Edit Game") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@game) do |f| %>
      <%= render 'shared/game_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/games/index.html.erb
<div class="jumbotron">
	<h1>Games</h1>
	<table id="games">
	<thead>
	  <tr>
		  <th>Name</th>
		  <th>Admin</th>
		  <th># of Players</th>
		  <th>Status</th>
	  </tr>
	</thead>
	<tbody>
	  <% @games.each do |game| %>
	    <tr>
	      <td><%= link_to game.name, game %></td>
		  <td><%= game.admin.name %></td>
		  <td><%= game.players.count %></td>
		  <td><%= game.status %></td>
		</tr>
	  <% end %>
	</tbody>
	</table>
</div>

app/views/games/new.html.erb
<% provide(:title, 'Create Game') %>
<h1>Create Game</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@game) do |f| %>
      <%= render 'shared/game_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Create Game", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<% provide(:title, @game.name) %>
<div class="jumbotron">
  <h1>Game Profile</h1>
  <div class="row">
    <aside class="col-md-4">
      <section class="game_info">
        <% @player = @game.players.find_by(assassin_id: current_user.id) %>
        <h4>
        	Name: <%= @game.name %>
          </br>
          </br>
          Description: <%= @game.description %>
          </br>
          </br>
          Admin: <%= link_to @game.admin.name, @game.admin %>
          </br>
          </br>
          Status: <%= @game.status %>
          <% if @game.in_progress %>
            <br>
            <br>
            Passcode: <%= @player.passcode %>
          <% end %>
          <% unless @game.winner.nil? %>
            <br>
            <br>
            Winner: <%= link_to @game.winner.name, @game.winner.assassin %>
          <% else %>
            <% if @player.try(:target) %>
              <br>
              <br>
              Current Target: <%= link_to Player.find(@player.target_id).name, Player.find(@player.target_id).assassin %>
              <br>
              <br>
              Target Defeated: 
              <%= link_to "Defeated", defeat_player_path(Player.find(@player.target_id)), class: "btn btn-lg btn-primary center" %>
            <% end %>
          <% end %>
        </h4>
      <% if !@player && @game.enrolling %>
        </br>
        <div class="center" >
          <%= link_to "Join Game", join_game_path(@game), method: :put, class: "btn btn-lg btn-primary center" %>
        </div>
      <% end %>
      <% if @game.admin == current_user && @game.enrolling %>
        </br>
        <div class="center" >
          <%= link_to "Start Game", start_game_path(@game), method: :put, class: "btn btn-lg btn-primary center" %>
        </div>
      <% end %>
      </section>
    </aside>
  </div>
</div>

<div class="jumbotron">
  <% if @game.players %>
    </br>
    <h1 class="center">Scoreboard</h1>
    <table id="players">
      <thead>
        <tr>
          <th>Name</th>
          <th>Status</th>
          <th>Points</th>
        </tr>
      </thead>
      <tbody>
        <% @game.players.each do |player| %>
          <tr>
            <td><%= link_to player.assassin.name, player.assassin %></td>
            <td><%= player.status %></td>
            <td><%= player.kills %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>