config/routes.rb
Rails.application.routes.draw do
  root to: 'static#home'

  get 'about'   => 'static#about'
  get 'signup' => 'assassins#new'

  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get  'players/:id/defeat', to: 'players#defeat', as: 'defeat_player'
  patch 'players/:id/vanquish', to: 'players#vanquish', as: 'vanquish_player'

  resources :assassins
  resources :games do
    member do
      put :join
      put :start
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The fun office nerf game
    by <a href="https://linkedin.com/in/longgarrett">Garrett Long</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "about",  '/about' %></li>
      <li><%= link_to "home",   '/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Gotcha", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Players", assassins_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Games <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Games", games_path %></li>
              <li><%= link_to "My Games", games_path(:mode => "assassin_only") %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Create Game", new_game_path %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_assassin_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>